import { FlowSpec } from './models';

export const SHIPPING_FLOWS: Record<string, FlowSpec> = {
  blank: {
    vb: [880, 760],
    nodes: [
      { id: 'start', x: 20, y: 60, w: 120, text: 'Blank PO', type: 'start' },
      { id: 'alt', x: 180, y: 56, w: 150, text: 'Alternate Ship To?', type: 'dec' },
      { id: 'altA', x: 400, y: 46, w: 185, text: 'Alternate Ship To Address', type: 'end' },
      { id: 'dec', x: 190, y: 180, w: 120, text: 'Decorated?', type: 'dec' },
      { id: 'stuUp', x: 360, y: 150, w: 160, text: 'Ship to Us Upon Completion?', type: 'dec' },
      { id: 'ord', x: 600, y: 128, w: 185, text: 'Order Shipping Address', type: 'end' },
      { id: 'stuIn', x: 175, y: 320, w: 165, text: 'Ship to Us Instead of Decorator?', type: 'dec' },
      { id: 'first', x: 600, y: 322, w: 185, text: 'First Decorator Address', type: 'end' },
      { id: 'dw', x: 370, y: 480, w: 150, text: 'Destination Warehouse?', type: 'dec' },
      { id: 'dwA', x: 600, y: 480, w: 185, text: 'Destination Warehouse', type: 'end' },
      { id: 'ci', x: 370, y: 600, w: 150, text: 'Corporate Identity?', type: 'dec' },
      { id: 'ciA', x: 600, y: 585, w: 185, text: 'Corporate Identity Address', type: 'end' },
      { id: 'partA', x: 600, y: 670, w: 185, text: 'Partner Address', type: 'end' },
    ],
    edges: [
      { f: 'start', t: 'alt', from: 'r', to: 'l' },
      { f: 'alt', t: 'altA', from: 'r', to: 'l', label: 'yes' },
      { f: 'alt', t: 'dec', from: 'b', to: 't', label: 'no' },
      { f: 'dec', t: 'stuUp', from: 'r', to: 'l', label: 'no' },
      { f: 'dec', t: 'stuIn', from: 'b', to: 't', label: 'yes' },
      { f: 'stuUp', t: 'ord', from: 'r', to: 'l', label: 'no' },
      { f: 'stuUp', t: 'dw', from: 'b', to: 't', label: 'yes' },
      { f: 'stuIn', t: 'first', from: 'r', to: 'l', label: 'no' },
      { f: 'stuIn', t: 'dw', from: 'b', to: 'l', label: 'yes' },
      { f: 'dw', t: 'dwA', from: 'r', to: 'l', label: 'yes' },
      { f: 'dw', t: 'ci', from: 'b', to: 't', label: 'no' },
      { f: 'ci', t: 'ciA', from: 'r', to: 'l', label: 'yes' },
      { f: 'ci', t: 'partA', from: 'b', to: 'l', label: 'no' },
    ],
  },
  decorator: {
    vb: [880, 760],
    nodes: [
      { id: 'start', x: 20, y: 300, w: 120, text: 'Decorator PO', type: 'start' },
      { id: 'final', x: 180, y: 292, w: 165, text: 'Final PO? (no more decorator vendors)', type: 'dec' },
      { id: 'next', x: 410, y: 120, w: 215, text: 'Second & Beyond Decorator Address (ship to next decorator)', type: 'end' },
      { id: 'alt', x: 410, y: 300, w: 140, text: 'Alternate Ship To?', type: 'dec' },
      { id: 'altA', x: 640, y: 280, w: 200, text: 'Alternate Ship To Address', type: 'end' },
      { id: 'stu', x: 405, y: 410, w: 150, text: 'Ship to Us Upon Completion?', type: 'dec' },
      { id: 'ord', x: 640, y: 418, w: 200, text: 'Order Shipping Address (Customer)', type: 'end' },
      { id: 'dw', x: 410, y: 515, w: 140, text: 'Destination Warehouse?', type: 'dec' },
      { id: 'dwA', x: 640, y: 517, w: 200, text: 'Destination Warehouse', type: 'end' },
      { id: 'ci', x: 410, y: 620, w: 140, text: 'Corporate Identity?', type: 'dec' },
      { id: 'ciA', x: 640, y: 608, w: 200, text: 'Corporate Identity Address', type: 'end' },
      { id: 'partA', x: 640, y: 678, w: 200, text: 'Partner Address', type: 'end' },
    ],
    edges: [
      { f: 'start', t: 'final', from: 'r', to: 'l' },
      { f: 'final', t: 'next', from: 't', to: 'l', label: 'no, more vendors', lt: 0.55 },
      { f: 'final', t: 'alt', from: 'b', to: 't', label: 'yes' },
      { f: 'alt', t: 'altA', from: 'r', to: 'l', label: 'yes' },
      { f: 'alt', t: 'stu', from: 'b', to: 't', label: 'no' },
      { f: 'stu', t: 'ord', from: 'r', to: 'l', label: 'no' },
      { f: 'stu', t: 'dw', from: 'b', to: 't', label: 'yes' },
      { f: 'dw', t: 'dwA', from: 'r', to: 'l', label: 'yes' },
      { f: 'dw', t: 'ci', from: 'b', to: 't', label: 'no' },
      { f: 'ci', t: 'ciA', from: 'r', to: 'l', label: 'yes' },
      { f: 'ci', t: 'partA', from: 'b', to: 'l', label: 'no' },
    ],
  },
  supplier: {
    vb: [880, 760],
    nodes: [
      { id: 'start', x: 20, y: 300, w: 150, text: 'Supplier Decorated PO', type: 'start' },
      { id: 'final', x: 210, y: 292, w: 165, text: 'Final PO? (no more decorator vendors)', type: 'dec' },
      { id: 'next', x: 430, y: 120, w: 215, text: 'Second & Beyond Decorator Address (ship to next decorator)', type: 'end' },
      { id: 'alt', x: 430, y: 300, w: 140, text: 'Alternate Ship To?', type: 'dec' },
      { id: 'altA', x: 660, y: 280, w: 200, text: 'Alternate Ship To Address', type: 'end' },
      { id: 'stu', x: 425, y: 410, w: 150, text: 'Ship to Us Upon Completion?', type: 'dec' },
      { id: 'ord', x: 660, y: 418, w: 200, text: 'Order Shipping Address (Customer)', type: 'end' },
      { id: 'dw', x: 430, y: 515, w: 140, text: 'Destination Warehouse?', type: 'dec' },
      { id: 'dwA', x: 660, y: 517, w: 200, text: 'Destination Warehouse', type: 'end' },
      { id: 'ci', x: 430, y: 620, w: 140, text: 'Corporate Identity?', type: 'dec' },
      { id: 'ciA', x: 660, y: 608, w: 200, text: 'Corporate Identity Address', type: 'end' },
      { id: 'partA', x: 660, y: 678, w: 200, text: 'Partner Address', type: 'end' },
    ],
    edges: [
      { f: 'start', t: 'final', from: 'r', to: 'l' },
      { f: 'final', t: 'next', from: 't', to: 'l', label: 'no, more vendors', lt: 0.55 },
      { f: 'final', t: 'alt', from: 'b', to: 't', label: 'yes' },
      { f: 'alt', t: 'altA', from: 'r', to: 'l', label: 'yes' },
      { f: 'alt', t: 'stu', from: 'b', to: 't', label: 'no' },
      { f: 'stu', t: 'ord', from: 'r', to: 'l', label: 'no' },
      { f: 'stu', t: 'dw', from: 'b', to: 't', label: 'yes' },
      { f: 'dw', t: 'dwA', from: 'r', to: 'l', label: 'yes' },
      { f: 'dw', t: 'ci', from: 'b', to: 't', label: 'no' },
      { f: 'ci', t: 'ciA', from: 'r', to: 'l', label: 'yes' },
      { f: 'ci', t: 'partA', from: 'b', to: 'l', label: 'no' },
    ],
  },
};

export const ALLOCATION_FLOWS: Record<string, FlowSpec> = {
  alloc: {
    vb: [1060, 760],
    nodes: [
      { id: 'start', x: 20, y: 350, w: 160, text: 'Size row (required qty)', type: 'start' },
      { id: 'd1', x: 210, y: 346, w: 160, text: 'Available stock ≥ required?', type: 'dec' },
      { id: 'e1', x: 450, y: 40, w: 200, text: 'All Stock, reserve inventory', type: 'end' },
      { id: 'dsp', x: 430, y: 346, w: 160, text: 'Some stock available? (partial)', type: 'dec' },
      { id: 'd3', x: 660, y: 170, w: 150, text: 'Backorder mode ON?', type: 'dec' },
      { id: 'e2', x: 850, y: 108, w: 190, text: 'Covered = Stock; shortfall = Backorder (bell)', type: 'end' },
      { id: 'e3', x: 850, y: 238, w: 190, text: 'Covered = Stock; remainder → new DropShip line', type: 'end' },
      { id: 'd4', x: 660, y: 450, w: 150, text: 'Backorder mode ON?', type: 'dec' },
      { id: 'e4', x: 850, y: 390, w: 190, text: 'Stock qty 0; full qty = Backorder', type: 'end' },
      { id: 'd5', x: 655, y: 580, w: 160, text: 'Every size on the line is zero?', type: 'dec' },
      { id: 'e5', x: 855, y: 540, w: 190, text: 'Flip whole line to DropShip (in-place)', type: 'end' },
      { id: 'e6', x: 855, y: 655, w: 190, text: 'Size removed; full qty → DropShip line', type: 'end' },
    ],
    edges: [
      { f: 'start', t: 'd1', from: 'r', to: 'l' },
      { f: 'd1', t: 'e1', from: 't', to: 'l', label: 'yes' },
      { f: 'd1', t: 'dsp', from: 'r', to: 'l', label: 'no' },
      { f: 'dsp', t: 'd3', from: 't', to: 'l', label: 'partial' },
      { f: 'dsp', t: 'd4', from: 'b', to: 'l', label: 'all zero' },
      { f: 'd3', t: 'e2', from: 't', to: 'l', label: 'yes' },
      { f: 'd3', t: 'e3', from: 'b', to: 'l', label: 'no' },
      { f: 'd4', t: 'e4', from: 't', to: 'l', label: 'yes' },
      { f: 'd4', t: 'd5', from: 'b', to: 't', label: 'no' },
      { f: 'd5', t: 'e5', from: 'r', to: 'l', label: 'yes' },
      { f: 'd5', t: 'e6', from: 'b', to: 'l', label: 'no' },
    ],
  },
  warehouse: {
    vb: [780, 900],
    nodes: [
      { id: 'start', x: 40, y: 20, w: 220, text: 'Resolve warehouse for the size', type: 'start' },
      { id: 'p1', x: 60, y: 120, w: 190, text: 'Primary has stock?', type: 'dec' },
      { id: 'a1', x: 350, y: 118, w: 200, text: 'Allocate from Primary', type: 'end' },
      { id: 'p2', x: 60, y: 240, w: 190, text: 'Secondary has stock?', type: 'dec' },
      { id: 'a2', x: 350, y: 238, w: 200, text: 'Allocate from Secondary', type: 'end' },
      { id: 'p3', x: 60, y: 360, w: 190, text: 'Tertiary has stock?', type: 'dec' },
      { id: 'a3', x: 350, y: 358, w: 200, text: 'Allocate from Tertiary', type: 'end' },
      { id: 's', x: 55, y: 480, w: 200, text: 'Search Warehouses for Stock = ON?', type: 'dec' },
      { id: 'q', x: 350, y: 478, w: 190, text: 'Any other warehouse has stock?', type: 'dec' },
      { id: 'aq', x: 580, y: 476, w: 180, text: 'Allocate from that warehouse', type: 'end' },
      { id: 'def', x: 60, y: 620, w: 190, text: 'Default warehouse has stock?', type: 'dec' },
      { id: 'ad', x: 350, y: 618, w: 200, text: 'Allocate from Default', type: 'end' },
      { id: 'none', x: 350, y: 740, w: 210, text: 'No stock → DropShip / Backorder per allocation rules', type: 'end' },
    ],
    edges: [
      { f: 'start', t: 'p1', from: 'b', to: 't' },
      { f: 'p1', t: 'a1', from: 'r', to: 'l', label: 'yes' },
      { f: 'p1', t: 'p2', from: 'b', to: 't', label: 'no' },
      { f: 'p2', t: 'a2', from: 'r', to: 'l', label: 'yes' },
      { f: 'p2', t: 'p3', from: 'b', to: 't', label: 'no' },
      { f: 'p3', t: 'a3', from: 'r', to: 'l', label: 'yes' },
      { f: 'p3', t: 's', from: 'b', to: 't', label: 'no' },
      { f: 's', t: 'q', from: 'r', to: 'l', label: 'yes' },
      { f: 'q', t: 'aq', from: 'r', to: 'l', label: 'yes' },
      { f: 'q', t: 'def', from: 'b', to: 'r', label: 'no' },
      { f: 's', t: 'def', from: 'b', to: 't', label: 'no' },
      { f: 'def', t: 'ad', from: 'r', to: 'l', label: 'yes' },
      { f: 'def', t: 'none', from: 'b', to: 'l', label: 'no' },
    ],
  },
  transfer: {
    vb: [1000, 860],
    nodes: [
      { id: 'start', x: 40, y: 20, w: 230, text: 'Child line booking · Share Parent Inventory = ON', type: 'start' },
      { id: 'd1', x: 80, y: 120, w: 190, text: 'Matrix PO type = Stock?', type: 'dec' },
      { id: 'e0', x: 360, y: 118, w: 190, text: 'No transfer, line is DropShip', type: 'end' },
      { id: 'd2', x: 80, y: 235, w: 190, text: 'Child stock ≥ required?', type: 'dec' },
      { id: 'e1', x: 360, y: 233, w: 190, text: 'Child covers it, no transfer', type: 'end' },
      { id: 'd3', x: 80, y: 350, w: 190, text: 'Parent has inventory?', type: 'dec' },
      { id: 'e2', x: 360, y: 348, w: 210, text: 'No transfer → DropShip / Backorder rules', type: 'end' },
      { id: 'd4', x: 70, y: 465, w: 210, text: 'Same warehouse type, or child stock = 0?', type: 'dec' },
      { id: 'e3', x: 360, y: 463, w: 210, text: 'Transfer blocked (different warehouse type)', type: 'end' },
      { id: 'act', x: 90, y: 590, w: 190, text: 'Transfer min(gap, parent) via FIFO lots → child', type: 'end' },
      { id: 'd5', x: 80, y: 710, w: 190, text: 'Gap fully covered?', type: 'dec' },
      { id: 'e4', x: 360, y: 688, w: 210, text: 'Child now covers required → Stock', type: 'end' },
      { id: 'e5', x: 360, y: 768, w: 210, text: 'Partial transfer → remainder Backorder / DropShip', type: 'end' },
    ],
    edges: [
      { f: 'start', t: 'd1', from: 'b', to: 't' },
      { f: 'd1', t: 'e0', from: 'r', to: 'l', label: 'no' },
      { f: 'd1', t: 'd2', from: 'b', to: 't', label: 'yes' },
      { f: 'd2', t: 'e1', from: 'r', to: 'l', label: 'yes' },
      { f: 'd2', t: 'd3', from: 'b', to: 't', label: 'no' },
      { f: 'd3', t: 'e2', from: 'r', to: 'l', label: 'no' },
      { f: 'd3', t: 'd4', from: 'b', to: 't', label: 'yes' },
      { f: 'd4', t: 'e3', from: 'r', to: 'l', label: 'no' },
      { f: 'd4', t: 'act', from: 'b', to: 't', label: 'yes' },
      { f: 'act', t: 'd5', from: 'b', to: 't' },
      { f: 'd5', t: 'e4', from: 'r', to: 'l', label: 'yes' },
      { f: 'd5', t: 'e5', from: 'b', to: 'l', label: 'no' },
    ],
  },
};
